### ISSUE TITLE
[DOCS] - Add explanations to README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by Slawomir-DKl** [kat-kan/kawqa-gad-playwright#79]
## ✏️ Description

I propose adding some explanations for less obvious parts of the README and CONTRIBUTING documents

## 🔧 Why We Need This

As a relatively new user of Playwright, I'd like to know why e.g. vscode-icons is recommended as an optional plugin to install. Also, some steps in contributing guidelines are not clear to me.

Of course, I can do all the edits, but I would need some explanations.

## 🚀 Proposed Correction or Addition

Contributing.md:
1. Add an explanation of the "with-deps chromium" option. I don't understand, why I should add this command. If it is decided to skip testing on Firefox and Webkit, please add this information, too.
2. Explain what e-mail and password are needed in the `.env` file and how to obtain the data (for users starting work in GAD)

Readme.md:
1. Explain what every plugin does (if it is not obvious) or why it is recommended in the project. A nice and short explanation is in the case of Thunder Client - `for making quick API requests within VS Code`. Some of the plugins are obvious to me, but some (e.g. vscode-icons) are not.

It would be useful to write some troubleshooting (e.g. as the last part of Readme.md) - what to do if in the initial test run you got a lot of 401 etc.

## ✅ Documentation fix checklist

- [x] I created a descriptive title for this documentation fix
- [x] I checked that a similar documentation issue hasn't been reported yet
- [x] I assigned the issue or added `help-wanted` label
- [x] I assigned the documentation fix or added appropriate labels

**Comment by kat-kan** [comment]
Wonderful, thanks for the feedback to README and CONTRIBUTING @Slawomir-DKl :)
