### ISSUE TITLE
Fix future-date test from articles-post file 

### ISSUE THREAD

**Issue by Slawomir-DKl** [kat-kan/kawqa-gad-playwright#97]
## ✏️ Description

Method `toISOString()` creates a date in the format with milliseconds, and GAD requires a format without milliseconds. Therefore the test is always green, regardless of the operator used in the line `date.setFullYear(date.getFullYear() + 1);` (you can change + with - and still get the 422 code, even if the date is from the past).
The solution is to add `.split('.')[0] + 'Z'` after the `toISOString()` method, e.g.:
```typescript
const futureDateFormatted: string = date.toISOString().split('.')[0] + 'Z';
```

Instead we could use the variables `customDate.pastDate` and `customDate.futureDate` I've created in Pull Request no. 96 (of course, after merging the latter PR into main branch)

## ✅ Problem report checklist

- [x] I created a descriptive title for this problem report
- [x] I checked that a similar issue hasn't been reported yet
- [x] I assigned the problem report or added appropriate labels

**Comment by kat-kan** [comment]
@Slawomir-DKl can you please double check on Your side?
While I agree using the generator for dates is much better approach and I am happy to change test to use it, I can not reproduce the problem with dates on the newest version of GAD. 
It appears to me that GAD accepts both formats
![image](https://github.com/kat-kan/kawqa-gad-playwright/assets/17500766/a5ee8921-2344-40fc-9773-c54b8204c0ee)

**Comment by Slawomir-DKl** [comment]
@kat-kan You're right. In the latest version of GAD (2.6.5) the date validation patterns were fixed  - see the [Release notes](https://github.com/jaktestowac/gad-gui-api-demo/releases/tag/v2.6.5). Therefore we can leave `toISOString()` method as it will be working from now on (in fact the method alone will be better solution now because it would allow to detect potential problems with date validation during future regression tests)

**Comment by kat-kan** [comment]
@Slawomir-DKl thank You for checking this, indeed it's mentioned in release notes, I didn't notice
I spent some time trying to include this new feature in our tests. Please let me know what You think!

**Comment by kat-kan** [comment]
@Slawomir-DKl I've just added Your suggestion :)
